name: 📋 Task
description: Development task or improvement (for maintainers)
title: "[Task]: "
labels: ["task"]
body:
  - type: dropdown
    id: phase
    attributes:
      label: Development Phase
      description: Which phase is this task part of?
      options:
        - Phase 1 - Foundation
        - Phase 2 - Core API
        - Phase 3 - Background Jobs
        - Phase 4 - IaC & Deployment
        - Phase 5 - Open Source Prep
        - Phase 6 - Advanced Features
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Implement database models for packages table
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Model created in app/models/package.py
        - [ ] Migration generated and tested
        - [ ] Unit tests written
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Technical Notes
      description: Implementation details, references, etc.
      placeholder: |
        - See architecture doc section X
        - Depends on #123
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (blocking)
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Time Estimate
      description: Rough estimate in hours or days
      placeholder: e.g., 2-4 hours, 1 day
    validations:
      required: false
